### ISSUE TITLE
CAN'T START

### ISSUE THREAD

**Issue by karneaud** [lynxtp/docker-lein#9]
downloaded and tried running your image via kitematic. From the logs

> Downloading Leiningen to /srv/lein/self-installs/leiningen-2.6.1-standalone.jar now...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 100   605    0   605    0     0    584      0 --:--:--  0:00:01 --:--:--   585
>   0 14.6M    0 16384    0     0   9491      0  0:26:56  0:00:01  0:26:55  9491  11 14.6M   11 1664k    0     0   610k      0  0:00:24  0:00:02  0:00:22 1648k  38 14.6M   38 5749k    0     0  1540k      0  0:00:09  0:00:03  0:00:06 2859k  65 14.6M   65 9813k    0     0  2076k      0  0:00:07  0:00:04  0:00:03 3265k  93 14.6M   93 13.6M    0     0  2441k      0  0:00:06  0:00:05  0:00:01 3489k 100 14.6M  100 14.6M    0     0  2491k      0  0:00:06  0:00:06 --:--:-- 3491k
> Leiningen is a tool for working with Clojure projects.
> Several tasks are available:
> change              Rewrite project.clj by applying a function.
> check               Check syntax and warn on reflection.
> classpath           Print the classpath of the current project.
> clean               Remove all files from project's target-path.
> compile             Compile Clojure source into .class files.
> deploy              Build and deploy jar to remote repository.
> deps                Download all dependencies.
> do                  Higher-order task to perform other tasks in succession.
> help                Display a list of tasks or help for a given task.
> install             Install the current project to the local repository.
> jar                 Package up all the project's files into a jar file.
> javac               Compile Java source files.
> new                 Generate project scaffolding based on a template.
> plugin              DEPRECATED. Please use the :user profile instead.
> pom                 Write a pom.xml file to disk for Maven interoperability.
> release             Perform :release-tasks.
> repl                Start a repl session either with the current project or standalone.
> retest              Run only the test namespaces which failed last time around.
> run                 Run a -main function with optional command-line arguments.
> search              Search remote maven repositories for matching jars.
> show-profiles       List all available profiles or display one if given an argument.
> test                Run the project's tests.
> trampoline          Run a task without nesting the project's JVM inside Leiningen's.
> uberjar             Package up the project files and dependencies into a jar file.
> update-in           Perform arbitrary transformations on your project map.
> upgrade             Upgrade Leiningen to specified version or latest stable.
> vcs                 Interact with the version control system.
> version             Print version for Leiningen and the current JVM.
> with-profile        Apply the given task with the profile(s) specified.
> Run `lein help $TASK` for details.
> Global Options:
>   -o             Run a task offline.
>   -U             Run a task after forcing update of snapshots.
>   -h, --help     Print this help or help for a specific task.
>   -v, --version  Print Leiningen's version.
> These aliases are available:
> downgrade, expands to upgrade
> See also: readme, faq, tutorial, news, sample, profiles, deploying, gpg,
> mixed-source, templates, and copying.
> Leiningen is a tool for working with Clojure projects.
> Several tasks are available:
> change              Rewrite project.clj by applying a function.
> check               Check syntax and warn on reflection.
> classpath           Print the classpath of the current project.
> clean               Remove all files from project's target-path.
> compile             Compile Clojure source into .class files.
> deploy              Build and deploy jar to remote repository.
> deps                Download all dependencies.
> do                  Higher-order task to perform other tasks in succession.
> help                Display a list of tasks or help for a given task.
> install             Install the current project to the local repository.
> jar                 Package up all the project's files into a jar file.
> javac               Compile Java source files.
> new                 Generate project scaffolding based on a template.
> plugin              DEPRECATED. Please use the :user profile instead.
> pom                 Write a pom.xml file to disk for Maven interoperability.
> release             Perform :release-tasks.
> repl                Start a repl session either with the current project or standalone.
> retest              Run only the test namespaces which failed last time around.
> run                 Run a -main function with optional command-line arguments.
> search              Search remote maven repositories for matching jars.
> show-profiles       List all available profiles or display one if given an argument.
> test                Run the project's tests.
> trampoline          Run a task without nesting the project's JVM inside Leiningen's.
> uberjar             Package up the project files and dependencies into a jar file.
> update-in           Perform arbitrary transformations on your project map.
> upgrade             Upgrade Leiningen to specified version or latest stable.
> vcs                 Interact with the version control system.
> version             Print version for Leiningen and the current JVM.
> with-profile        Apply the given task with the profile(s) specified.
> Run `lein help $TASK` for details.
> Global Options:
>   -o             Run a task offline.
>   -U             Run a task after forcing update of snapshots.
>   -h, --help     Print this help or help for a specific task.
>   -v, --version  Print Leiningen's version.
> These aliases are available:
> downgrade, expands to upgrade
> See also: readme, faq, tutorial, news, sample, profiles, deploying, gpg,
> mixed-source, templates, and copying.
> Leiningen is a tool for working with Clojure projects.
> Several tasks are available:
> change              Rewrite project.clj by applying a function.
> check               Check syntax and warn on reflection.
> classpath           Print the classpath of the current project.
> clean               Remove all files from project's target-path.
> compile             Compile Clojure source into .class files.
> deploy              Build and deploy jar to remote repository.
> deps                Download all dependencies.
> do                  Higher-order task to perform other tasks in succession.
> help                Display a list of tasks or help for a given task.
> install             Install the current project to the local repository.
> jar                 Package up all the project's files into a jar file.
> javac               Compile Java source files.
> new                 Generate project scaffolding based on a template.
> plugin              DEPRECATED. Please use the :user profile instead.
> pom                 Write a pom.xml file to disk for Maven interoperability.
> release             Perform :release-tasks.
> repl                Start a repl session either with the current project or standalone.
> retest              Run only the test namespaces which failed last time around.
> run                 Run a -main function with optional command-line arguments.
> search              Search remote maven repositories for matching jars.
> show-profiles       List all available profiles or display one if given an argument.
> test                Run the project's tests.
> trampoline          Run a task without nesting the project's JVM inside Leiningen's.
> uberjar             Package up the project files and dependencies into a jar file.
> update-in           Perform arbitrary transformations on your project map.
> upgrade             Upgrade Leiningen to specified version or latest stable.
> vcs                 Interact with the version control system.
> version             Print version for Leiningen and the current JVM.
> with-profile        Apply the given task with the profile(s) specified.
> Run `lein help $TASK` for details.
> Global Options:
>   -o             Run a task offline.
>   -U             Run a task after forcing update of snapshots.
>   -h, --help     Print this help or help for a specific task.
>   -v, --version  Print Leiningen's version.
> These aliases are available:
> downgrade, expands to upgrade
> See also: readme, faq, tutorial, news, sample, profiles, deploying, gpg,
> mixed-source, templates, and copying.

**Comment by carrete** [comment]
Hey @karneaud, thanks a lot for trying this out and for taking the time to create this issue. However, this looks like expected behavior to me. This container is meant to be created and run on the command-line, or used to build a web service written in clojure or clojurescript. What is it that you expected would show up in Kitematic? Again, thanks!

**Comment by karneaud** [comment]
@carrete well maybe so but soon after the serve seems to stop and I get disconnected from the box and this is right have the message

**Comment by carrete** [comment]
> after the serve seems to stop and I get disconnected from the box and this is right have the message

That's correct. What's happening is that the leiningen command-line application (see https://leiningen.org/) is being run. In your case you see a help message about what commands are available and how to run them. Are you familiar with leiningen? It's not a webserver. It won't display a website. It's meant to exit after it completes its task.

**Comment by karneaud** [comment]
aaaahhhhh i see...I was hoping to run my project off of it....my bad
